#!/bin/bash
#
# N8CQ Installer
apt update
apt full-upgrade -y
apt install git build-essential mc zip unzip p7zip-full btop htop hostapd dnsmasq apache2-utils libexpat1 ssl-cert apache2 php php-fpm php-cgi php-json php-opcache php-pdo php-readline libapache2-mod-php php php-common php-curl php-dev php-gd php-pear php-imagick php-mysql php-ps php-xsl g++ make cmake libsigc++-2.0-dev nodejs libgsm1-dev libudev-dev libpopt-dev tcl-dev libgcrypt20-dev libspeex-dev libasound2-dev alsa-utils libjsoncpp-dev libopus-dev rtl-sdr libcurl4-openssl-dev libogg-dev librtlsdr-dev groff doxygen graphviz python3-serial -y
apt install libpython3-dev libpython3-stdlib libpython3.11-dev libpython3.11-minimal libpython3.11-stdlib libpython3.11 python-apt-common python-is-python3 python-xmlschema-doc python3-apt python3-blinker python3-cffi-backend python3-click python3-colorama python3-cryptography python3-dbus python3-dev python3-distro-info python3-distro python3-distutils-extra python3-distutils python3-dnspython python3-elementpath python3-flask python3-gi python3-httplib2 python3-itsdangerous python3-jinja2 python3-jwt python3-lazr.restfulclient python3-lazr.uri python3-ldb python3-lib2to3 python3-markdown-it python3-markupsafe python3-mdurl python3-minimal python3-netifaces python3-oauthlib python3-pip-whl python3-pip python3-pkg-resources python3-pyasn1 python3-pygments python3-pyparsing python3-rich python3-samba python3-serial python3-setuptools python3-six python3-software-properties python3-talloc python3-tdb python3-wadllib python3-werkzeug python3-wheel python3-xdg python3-xmlschema python3-yaml python3.11-dev python3.11-minimal python3.11 python3
wget https://github.com/JiriSko/amixer-webui/releases/download/v1.0.0-rc/amixer-webui_1.0.0-rc_all.deb
dpkg -i amixer-webui_1.0.0-rc_all.deb
